### ISSUE TITLE
Profile create, edit

### ISSUE THREAD

**Issue by Janhavi-23** [deepr41/WolfJobs#10]

**Comment by deepr41** [comment]
![image](https://github.com/deepr41/WolfJobs/assets/22258487/34e9e8e5-c199-4bd2-95ba-41755ba74bae)
![image](https://github.com/deepr41/WolfJobs/assets/22258487/7d65a6af-0630-4c18-8416-a2f564c72275)

Added profile edit screen

**Comment by shafa112** [comment]
We can edit the manager and applicant profile properly, thanks. Closing the issue.
