### ISSUE TITLE
Change packaging from webpack to vite

### ISSUE THREAD

**Issue by deepr41** [deepr41/WolfJobs#3]

**Comment by deepr41** [comment]
Why this feature?
Vite is the industry standard for building webapps with smaller bundle sizes and smaller build times.
It will significantly reduce build and testing time on the CI/CD pipeline.

**Comment by shafa112** [comment]
Thanks, this has highly optimized the development server, providing near-instantaneous updates and overall pipeline performance has increased as compared Webpack.
