### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by Janhavi-23** [deepr41/WolfJobs#6]

**Comment by Janhavi-23** [comment]
Landing page have been updated then before

**Comment by deepr41** [comment]
<img width="1494" alt="Screenshot 2023-10-19 at 2 18 39 PM" src="https://github.com/deepr41/WolfJobs/assets/22258487/c92c0ed7-f8d8-426a-be62-84d824b6e306">

**Comment by shafa112** [comment]
We added Images and text Description to show what the website is used for and have Sign up and Login buttons. This has made the landing page of website more user friendly. Thank you.
