### ISSUE TITLE
All jobs listing 

### ISSUE THREAD

**Issue by Janhavi-23** [deepr41/WolfJobs#7]

**Comment by Janhavi-23** [comment]
Applicant view has separate tab to view all open jobs and can view description of each

**Comment by shafa112** [comment]
Managers can now track his own job listing under 'My Listings' as well as look at 'All jobs' that have been posted by other managers. Applicants can now track their applications in a better view. They have different tabs for the jobs they have applied to and different tab for all the jobs that are listed on WolfJobs by different NCSU recruiters.
